package:
  name: gmp
  version: "6.1.2"

source:
  fn: gmp-6.1.2.tar.xz
  url: https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz
  md5: f58fa8001d60c4c77595fbbb62b63c1d

build:
  number: 0

test:
  files:
    - test.c
    - test.cc

about:
  home: http://gmplib.org/
  license: GPL-3
  license_family: GPL3
  summary: "The GNU Multiple Precision Arithmetic Library"
  description: |
    GMP is a free library for arbitrary precision arithmetic, operating on
    signed integers, rational numbers, and floating-point numbers. There is
    no practical limit to the precision except the ones implied by the
    available memory in the machine GMP runs on. GMP has a rich set of
    functions, and the functions have a regular interface.
  doc_url: https://gmplib.org/manual/
  dev_url: https://gmplib.org/repo/
